--CREATE USER
create user dbt_user password='dbt-pass'
LOGIN_NAME='USER'
DEFAULT_ROLE= ACCOUNTADMIN
MUST_CHANGE_PASSWORD=FALSE;

-- GRANT ROLE TO dbt_user
GRANT ROLE ACCOUNTADMIN TO USER USER;

--GRANT ACCESS TO THE DATABASE
GRANT USAGE ON DATABASE FINANCE_DB TO ROLE ACCOUNTADMIN;
--GRANT ACCESS TO THE SCHEMA
GRANT USAGE ON SCHEMA RAW TO ROLE ACCOUNTADMIN;
--GRANT ACCESS TO THE WAREHOUSE
GRANT USAGE ON WAREHOUSE FINANCE_WH TO ROLE ACCOUNTADMIN;
--GRANT TABLE ACCESS TO THE ROLE
GRANT SELECT,INSERT,DELETE,UPDATE ON ALL TABLES IN SCHEMA FINANCE_DB.RAW TO ROLE ACCOUNTADMIN;
SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();