CREATE OR REPLACE WAREHOUSE FINANCE_WH
WITH WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60

AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;
CREATE OR REPLACE DATABASE FINANCE_DB;
CREATE OR REPLACE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.CUSTOMERS
(
ID VARCHAR PRIMARY KEY,
ZIP_CODE INT,
CITY VARCHAR,
STATE VARCHAR
);
CREATE OR REPLACE TABLE RAW.ORDERS
(
ID VARCHAR PRIMARY KEY,
CUSTOMER_ID VARCHAR,
ORDER_STATUS VARCHAR,
ORDER_DATE DATE,
ORDER_APPROVED DATE,
ORDER_DELIVERED DATE,
ORDER_ESTIMATED DATE
);

CREATE OR REPLACE TABLE RAW.ORDER_ITEMS
(
ORDER_ID VARCHAR,
PRODUCT_ID VARCHAR,
SELLER_ID VARCHAR,
PRICE INT,
SHIPPING_CHARGES INT
);
CREATE OR REPLACE TABLE RAW.PRODUCTS
(
ID VARCHAR PRIMARY KEY ,
CATEGORY STRING,
PRODUCT_WEIGHT_G INT,
PRODUCT_LENGTH_CM INT,
PRODUCT_HEIGHT_CM INT,
PRODUCT_WIDTH_CM INT
);
drop table FINANCE_DB.RAW.MY_FIRST_DBT_MODEL

